# Configuration globale
app:
  port: 5000         
  debug: true        
  host: "127.0.0.1"  

# Chemins des répertoires
directories:
  markdown: "markdowns"   
  exports: "exports"      

# Styles par défaut
styles:
  font-family: "Arial, sans-serif"
  font-size: "14px"
  color: "#000000"        
  background-color: "#ffffff"

# Syntaxe personnalisée
syntax:
  progress-bar-colors:    
    - "blue"
    - "green"
    - "red"
    - "yellow"
  block-types:            
    "!": "bg-yellow-100 text-yellow-800"
    "i": "bg-blue-100 text-blue-800"
    "x": "bg-red-100 text-red-800"
    "✓": "bg-green-100 text-green-800"
